// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: moonranger_rover.proto

package moonranger_rover;

public final class MoonrangerRover {
  private MoonrangerRover() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface GoalOrBuilder extends
      // @@protoc_insertion_point(interface_extends:moonranger_rover.Goal)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>float x_coordinate_m = 1;</code>
     */
    float getXCoordinateM();

    /**
     * <code>float y_coordinate_m = 2;</code>
     */
    float getYCoordinateM();

    /**
     * <code>float x_rad_m = 3;</code>
     */
    float getXRadM();

    /**
     * <code>float y_rad_m = 4;</code>
     */
    float getYRadM();

    /**
     * <code>float orientation_rad = 5;</code>
     */
    float getOrientationRad();
  }
  /**
   * Protobuf type {@code moonranger_rover.Goal}
   */
  public  static final class Goal extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:moonranger_rover.Goal)
      GoalOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Goal.newBuilder() to construct.
    private Goal(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Goal() {
      xCoordinateM_ = 0F;
      yCoordinateM_ = 0F;
      xRadM_ = 0F;
      yRadM_ = 0F;
      orientationRad_ = 0F;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Goal(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 13: {

              xCoordinateM_ = input.readFloat();
              break;
            }
            case 21: {

              yCoordinateM_ = input.readFloat();
              break;
            }
            case 29: {

              xRadM_ = input.readFloat();
              break;
            }
            case 37: {

              yRadM_ = input.readFloat();
              break;
            }
            case 45: {

              orientationRad_ = input.readFloat();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return moonranger_rover.MoonrangerRover.internal_static_moonranger_rover_Goal_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return moonranger_rover.MoonrangerRover.internal_static_moonranger_rover_Goal_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              moonranger_rover.MoonrangerRover.Goal.class, moonranger_rover.MoonrangerRover.Goal.Builder.class);
    }

    public static final int X_COORDINATE_M_FIELD_NUMBER = 1;
    private float xCoordinateM_;
    /**
     * <code>float x_coordinate_m = 1;</code>
     */
    public float getXCoordinateM() {
      return xCoordinateM_;
    }

    public static final int Y_COORDINATE_M_FIELD_NUMBER = 2;
    private float yCoordinateM_;
    /**
     * <code>float y_coordinate_m = 2;</code>
     */
    public float getYCoordinateM() {
      return yCoordinateM_;
    }

    public static final int X_RAD_M_FIELD_NUMBER = 3;
    private float xRadM_;
    /**
     * <code>float x_rad_m = 3;</code>
     */
    public float getXRadM() {
      return xRadM_;
    }

    public static final int Y_RAD_M_FIELD_NUMBER = 4;
    private float yRadM_;
    /**
     * <code>float y_rad_m = 4;</code>
     */
    public float getYRadM() {
      return yRadM_;
    }

    public static final int ORIENTATION_RAD_FIELD_NUMBER = 5;
    private float orientationRad_;
    /**
     * <code>float orientation_rad = 5;</code>
     */
    public float getOrientationRad() {
      return orientationRad_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (xCoordinateM_ != 0F) {
        output.writeFloat(1, xCoordinateM_);
      }
      if (yCoordinateM_ != 0F) {
        output.writeFloat(2, yCoordinateM_);
      }
      if (xRadM_ != 0F) {
        output.writeFloat(3, xRadM_);
      }
      if (yRadM_ != 0F) {
        output.writeFloat(4, yRadM_);
      }
      if (orientationRad_ != 0F) {
        output.writeFloat(5, orientationRad_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (xCoordinateM_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(1, xCoordinateM_);
      }
      if (yCoordinateM_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(2, yCoordinateM_);
      }
      if (xRadM_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(3, xRadM_);
      }
      if (yRadM_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(4, yRadM_);
      }
      if (orientationRad_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(5, orientationRad_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof moonranger_rover.MoonrangerRover.Goal)) {
        return super.equals(obj);
      }
      moonranger_rover.MoonrangerRover.Goal other = (moonranger_rover.MoonrangerRover.Goal) obj;

      boolean result = true;
      result = result && (
          java.lang.Float.floatToIntBits(getXCoordinateM())
          == java.lang.Float.floatToIntBits(
              other.getXCoordinateM()));
      result = result && (
          java.lang.Float.floatToIntBits(getYCoordinateM())
          == java.lang.Float.floatToIntBits(
              other.getYCoordinateM()));
      result = result && (
          java.lang.Float.floatToIntBits(getXRadM())
          == java.lang.Float.floatToIntBits(
              other.getXRadM()));
      result = result && (
          java.lang.Float.floatToIntBits(getYRadM())
          == java.lang.Float.floatToIntBits(
              other.getYRadM()));
      result = result && (
          java.lang.Float.floatToIntBits(getOrientationRad())
          == java.lang.Float.floatToIntBits(
              other.getOrientationRad()));
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + X_COORDINATE_M_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getXCoordinateM());
      hash = (37 * hash) + Y_COORDINATE_M_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getYCoordinateM());
      hash = (37 * hash) + X_RAD_M_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getXRadM());
      hash = (37 * hash) + Y_RAD_M_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getYRadM());
      hash = (37 * hash) + ORIENTATION_RAD_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getOrientationRad());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static moonranger_rover.MoonrangerRover.Goal parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static moonranger_rover.MoonrangerRover.Goal parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static moonranger_rover.MoonrangerRover.Goal parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static moonranger_rover.MoonrangerRover.Goal parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static moonranger_rover.MoonrangerRover.Goal parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static moonranger_rover.MoonrangerRover.Goal parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static moonranger_rover.MoonrangerRover.Goal parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static moonranger_rover.MoonrangerRover.Goal parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static moonranger_rover.MoonrangerRover.Goal parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static moonranger_rover.MoonrangerRover.Goal parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static moonranger_rover.MoonrangerRover.Goal parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static moonranger_rover.MoonrangerRover.Goal parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(moonranger_rover.MoonrangerRover.Goal prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code moonranger_rover.Goal}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:moonranger_rover.Goal)
        moonranger_rover.MoonrangerRover.GoalOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return moonranger_rover.MoonrangerRover.internal_static_moonranger_rover_Goal_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return moonranger_rover.MoonrangerRover.internal_static_moonranger_rover_Goal_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                moonranger_rover.MoonrangerRover.Goal.class, moonranger_rover.MoonrangerRover.Goal.Builder.class);
      }

      // Construct using moonranger_rover.MoonrangerRover.Goal.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        xCoordinateM_ = 0F;

        yCoordinateM_ = 0F;

        xRadM_ = 0F;

        yRadM_ = 0F;

        orientationRad_ = 0F;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return moonranger_rover.MoonrangerRover.internal_static_moonranger_rover_Goal_descriptor;
      }

      @java.lang.Override
      public moonranger_rover.MoonrangerRover.Goal getDefaultInstanceForType() {
        return moonranger_rover.MoonrangerRover.Goal.getDefaultInstance();
      }

      @java.lang.Override
      public moonranger_rover.MoonrangerRover.Goal build() {
        moonranger_rover.MoonrangerRover.Goal result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public moonranger_rover.MoonrangerRover.Goal buildPartial() {
        moonranger_rover.MoonrangerRover.Goal result = new moonranger_rover.MoonrangerRover.Goal(this);
        result.xCoordinateM_ = xCoordinateM_;
        result.yCoordinateM_ = yCoordinateM_;
        result.xRadM_ = xRadM_;
        result.yRadM_ = yRadM_;
        result.orientationRad_ = orientationRad_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof moonranger_rover.MoonrangerRover.Goal) {
          return mergeFrom((moonranger_rover.MoonrangerRover.Goal)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(moonranger_rover.MoonrangerRover.Goal other) {
        if (other == moonranger_rover.MoonrangerRover.Goal.getDefaultInstance()) return this;
        if (other.getXCoordinateM() != 0F) {
          setXCoordinateM(other.getXCoordinateM());
        }
        if (other.getYCoordinateM() != 0F) {
          setYCoordinateM(other.getYCoordinateM());
        }
        if (other.getXRadM() != 0F) {
          setXRadM(other.getXRadM());
        }
        if (other.getYRadM() != 0F) {
          setYRadM(other.getYRadM());
        }
        if (other.getOrientationRad() != 0F) {
          setOrientationRad(other.getOrientationRad());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        moonranger_rover.MoonrangerRover.Goal parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (moonranger_rover.MoonrangerRover.Goal) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private float xCoordinateM_ ;
      /**
       * <code>float x_coordinate_m = 1;</code>
       */
      public float getXCoordinateM() {
        return xCoordinateM_;
      }
      /**
       * <code>float x_coordinate_m = 1;</code>
       */
      public Builder setXCoordinateM(float value) {
        
        xCoordinateM_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float x_coordinate_m = 1;</code>
       */
      public Builder clearXCoordinateM() {
        
        xCoordinateM_ = 0F;
        onChanged();
        return this;
      }

      private float yCoordinateM_ ;
      /**
       * <code>float y_coordinate_m = 2;</code>
       */
      public float getYCoordinateM() {
        return yCoordinateM_;
      }
      /**
       * <code>float y_coordinate_m = 2;</code>
       */
      public Builder setYCoordinateM(float value) {
        
        yCoordinateM_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float y_coordinate_m = 2;</code>
       */
      public Builder clearYCoordinateM() {
        
        yCoordinateM_ = 0F;
        onChanged();
        return this;
      }

      private float xRadM_ ;
      /**
       * <code>float x_rad_m = 3;</code>
       */
      public float getXRadM() {
        return xRadM_;
      }
      /**
       * <code>float x_rad_m = 3;</code>
       */
      public Builder setXRadM(float value) {
        
        xRadM_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float x_rad_m = 3;</code>
       */
      public Builder clearXRadM() {
        
        xRadM_ = 0F;
        onChanged();
        return this;
      }

      private float yRadM_ ;
      /**
       * <code>float y_rad_m = 4;</code>
       */
      public float getYRadM() {
        return yRadM_;
      }
      /**
       * <code>float y_rad_m = 4;</code>
       */
      public Builder setYRadM(float value) {
        
        yRadM_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float y_rad_m = 4;</code>
       */
      public Builder clearYRadM() {
        
        yRadM_ = 0F;
        onChanged();
        return this;
      }

      private float orientationRad_ ;
      /**
       * <code>float orientation_rad = 5;</code>
       */
      public float getOrientationRad() {
        return orientationRad_;
      }
      /**
       * <code>float orientation_rad = 5;</code>
       */
      public Builder setOrientationRad(float value) {
        
        orientationRad_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float orientation_rad = 5;</code>
       */
      public Builder clearOrientationRad() {
        
        orientationRad_ = 0F;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:moonranger_rover.Goal)
    }

    // @@protoc_insertion_point(class_scope:moonranger_rover.Goal)
    private static final moonranger_rover.MoonrangerRover.Goal DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new moonranger_rover.MoonrangerRover.Goal();
    }

    public static moonranger_rover.MoonrangerRover.Goal getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Goal>
        PARSER = new com.google.protobuf.AbstractParser<Goal>() {
      @java.lang.Override
      public Goal parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Goal(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Goal> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Goal> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public moonranger_rover.MoonrangerRover.Goal getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface TranslationPoseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:moonranger_rover.TranslationPose)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>float x_m = 1;</code>
     */
    float getXM();

    /**
     * <code>float y_m = 2;</code>
     */
    float getYM();

    /**
     * <code>float z_m = 3;</code>
     */
    float getZM();
  }
  /**
   * Protobuf type {@code moonranger_rover.TranslationPose}
   */
  public  static final class TranslationPose extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:moonranger_rover.TranslationPose)
      TranslationPoseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TranslationPose.newBuilder() to construct.
    private TranslationPose(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TranslationPose() {
      xM_ = 0F;
      yM_ = 0F;
      zM_ = 0F;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private TranslationPose(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 13: {

              xM_ = input.readFloat();
              break;
            }
            case 21: {

              yM_ = input.readFloat();
              break;
            }
            case 29: {

              zM_ = input.readFloat();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return moonranger_rover.MoonrangerRover.internal_static_moonranger_rover_TranslationPose_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return moonranger_rover.MoonrangerRover.internal_static_moonranger_rover_TranslationPose_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              moonranger_rover.MoonrangerRover.TranslationPose.class, moonranger_rover.MoonrangerRover.TranslationPose.Builder.class);
    }

    public static final int X_M_FIELD_NUMBER = 1;
    private float xM_;
    /**
     * <code>float x_m = 1;</code>
     */
    public float getXM() {
      return xM_;
    }

    public static final int Y_M_FIELD_NUMBER = 2;
    private float yM_;
    /**
     * <code>float y_m = 2;</code>
     */
    public float getYM() {
      return yM_;
    }

    public static final int Z_M_FIELD_NUMBER = 3;
    private float zM_;
    /**
     * <code>float z_m = 3;</code>
     */
    public float getZM() {
      return zM_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (xM_ != 0F) {
        output.writeFloat(1, xM_);
      }
      if (yM_ != 0F) {
        output.writeFloat(2, yM_);
      }
      if (zM_ != 0F) {
        output.writeFloat(3, zM_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (xM_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(1, xM_);
      }
      if (yM_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(2, yM_);
      }
      if (zM_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(3, zM_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof moonranger_rover.MoonrangerRover.TranslationPose)) {
        return super.equals(obj);
      }
      moonranger_rover.MoonrangerRover.TranslationPose other = (moonranger_rover.MoonrangerRover.TranslationPose) obj;

      boolean result = true;
      result = result && (
          java.lang.Float.floatToIntBits(getXM())
          == java.lang.Float.floatToIntBits(
              other.getXM()));
      result = result && (
          java.lang.Float.floatToIntBits(getYM())
          == java.lang.Float.floatToIntBits(
              other.getYM()));
      result = result && (
          java.lang.Float.floatToIntBits(getZM())
          == java.lang.Float.floatToIntBits(
              other.getZM()));
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + X_M_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getXM());
      hash = (37 * hash) + Y_M_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getYM());
      hash = (37 * hash) + Z_M_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getZM());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static moonranger_rover.MoonrangerRover.TranslationPose parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static moonranger_rover.MoonrangerRover.TranslationPose parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static moonranger_rover.MoonrangerRover.TranslationPose parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static moonranger_rover.MoonrangerRover.TranslationPose parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static moonranger_rover.MoonrangerRover.TranslationPose parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static moonranger_rover.MoonrangerRover.TranslationPose parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static moonranger_rover.MoonrangerRover.TranslationPose parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static moonranger_rover.MoonrangerRover.TranslationPose parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static moonranger_rover.MoonrangerRover.TranslationPose parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static moonranger_rover.MoonrangerRover.TranslationPose parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static moonranger_rover.MoonrangerRover.TranslationPose parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static moonranger_rover.MoonrangerRover.TranslationPose parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(moonranger_rover.MoonrangerRover.TranslationPose prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code moonranger_rover.TranslationPose}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:moonranger_rover.TranslationPose)
        moonranger_rover.MoonrangerRover.TranslationPoseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return moonranger_rover.MoonrangerRover.internal_static_moonranger_rover_TranslationPose_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return moonranger_rover.MoonrangerRover.internal_static_moonranger_rover_TranslationPose_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                moonranger_rover.MoonrangerRover.TranslationPose.class, moonranger_rover.MoonrangerRover.TranslationPose.Builder.class);
      }

      // Construct using moonranger_rover.MoonrangerRover.TranslationPose.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        xM_ = 0F;

        yM_ = 0F;

        zM_ = 0F;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return moonranger_rover.MoonrangerRover.internal_static_moonranger_rover_TranslationPose_descriptor;
      }

      @java.lang.Override
      public moonranger_rover.MoonrangerRover.TranslationPose getDefaultInstanceForType() {
        return moonranger_rover.MoonrangerRover.TranslationPose.getDefaultInstance();
      }

      @java.lang.Override
      public moonranger_rover.MoonrangerRover.TranslationPose build() {
        moonranger_rover.MoonrangerRover.TranslationPose result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public moonranger_rover.MoonrangerRover.TranslationPose buildPartial() {
        moonranger_rover.MoonrangerRover.TranslationPose result = new moonranger_rover.MoonrangerRover.TranslationPose(this);
        result.xM_ = xM_;
        result.yM_ = yM_;
        result.zM_ = zM_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof moonranger_rover.MoonrangerRover.TranslationPose) {
          return mergeFrom((moonranger_rover.MoonrangerRover.TranslationPose)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(moonranger_rover.MoonrangerRover.TranslationPose other) {
        if (other == moonranger_rover.MoonrangerRover.TranslationPose.getDefaultInstance()) return this;
        if (other.getXM() != 0F) {
          setXM(other.getXM());
        }
        if (other.getYM() != 0F) {
          setYM(other.getYM());
        }
        if (other.getZM() != 0F) {
          setZM(other.getZM());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        moonranger_rover.MoonrangerRover.TranslationPose parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (moonranger_rover.MoonrangerRover.TranslationPose) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private float xM_ ;
      /**
       * <code>float x_m = 1;</code>
       */
      public float getXM() {
        return xM_;
      }
      /**
       * <code>float x_m = 1;</code>
       */
      public Builder setXM(float value) {
        
        xM_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float x_m = 1;</code>
       */
      public Builder clearXM() {
        
        xM_ = 0F;
        onChanged();
        return this;
      }

      private float yM_ ;
      /**
       * <code>float y_m = 2;</code>
       */
      public float getYM() {
        return yM_;
      }
      /**
       * <code>float y_m = 2;</code>
       */
      public Builder setYM(float value) {
        
        yM_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float y_m = 2;</code>
       */
      public Builder clearYM() {
        
        yM_ = 0F;
        onChanged();
        return this;
      }

      private float zM_ ;
      /**
       * <code>float z_m = 3;</code>
       */
      public float getZM() {
        return zM_;
      }
      /**
       * <code>float z_m = 3;</code>
       */
      public Builder setZM(float value) {
        
        zM_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float z_m = 3;</code>
       */
      public Builder clearZM() {
        
        zM_ = 0F;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:moonranger_rover.TranslationPose)
    }

    // @@protoc_insertion_point(class_scope:moonranger_rover.TranslationPose)
    private static final moonranger_rover.MoonrangerRover.TranslationPose DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new moonranger_rover.MoonrangerRover.TranslationPose();
    }

    public static moonranger_rover.MoonrangerRover.TranslationPose getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TranslationPose>
        PARSER = new com.google.protobuf.AbstractParser<TranslationPose>() {
      @java.lang.Override
      public TranslationPose parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TranslationPose(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TranslationPose> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TranslationPose> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public moonranger_rover.MoonrangerRover.TranslationPose getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface RotationPoseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:moonranger_rover.RotationPose)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>float x_quat = 1;</code>
     */
    float getXQuat();

    /**
     * <code>float y_quat = 2;</code>
     */
    float getYQuat();

    /**
     * <code>float z_quat = 3;</code>
     */
    float getZQuat();

    /**
     * <code>float w_quat = 4;</code>
     */
    float getWQuat();
  }
  /**
   * Protobuf type {@code moonranger_rover.RotationPose}
   */
  public  static final class RotationPose extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:moonranger_rover.RotationPose)
      RotationPoseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use RotationPose.newBuilder() to construct.
    private RotationPose(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RotationPose() {
      xQuat_ = 0F;
      yQuat_ = 0F;
      zQuat_ = 0F;
      wQuat_ = 0F;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private RotationPose(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 13: {

              xQuat_ = input.readFloat();
              break;
            }
            case 21: {

              yQuat_ = input.readFloat();
              break;
            }
            case 29: {

              zQuat_ = input.readFloat();
              break;
            }
            case 37: {

              wQuat_ = input.readFloat();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return moonranger_rover.MoonrangerRover.internal_static_moonranger_rover_RotationPose_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return moonranger_rover.MoonrangerRover.internal_static_moonranger_rover_RotationPose_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              moonranger_rover.MoonrangerRover.RotationPose.class, moonranger_rover.MoonrangerRover.RotationPose.Builder.class);
    }

    public static final int X_QUAT_FIELD_NUMBER = 1;
    private float xQuat_;
    /**
     * <code>float x_quat = 1;</code>
     */
    public float getXQuat() {
      return xQuat_;
    }

    public static final int Y_QUAT_FIELD_NUMBER = 2;
    private float yQuat_;
    /**
     * <code>float y_quat = 2;</code>
     */
    public float getYQuat() {
      return yQuat_;
    }

    public static final int Z_QUAT_FIELD_NUMBER = 3;
    private float zQuat_;
    /**
     * <code>float z_quat = 3;</code>
     */
    public float getZQuat() {
      return zQuat_;
    }

    public static final int W_QUAT_FIELD_NUMBER = 4;
    private float wQuat_;
    /**
     * <code>float w_quat = 4;</code>
     */
    public float getWQuat() {
      return wQuat_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (xQuat_ != 0F) {
        output.writeFloat(1, xQuat_);
      }
      if (yQuat_ != 0F) {
        output.writeFloat(2, yQuat_);
      }
      if (zQuat_ != 0F) {
        output.writeFloat(3, zQuat_);
      }
      if (wQuat_ != 0F) {
        output.writeFloat(4, wQuat_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (xQuat_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(1, xQuat_);
      }
      if (yQuat_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(2, yQuat_);
      }
      if (zQuat_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(3, zQuat_);
      }
      if (wQuat_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(4, wQuat_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof moonranger_rover.MoonrangerRover.RotationPose)) {
        return super.equals(obj);
      }
      moonranger_rover.MoonrangerRover.RotationPose other = (moonranger_rover.MoonrangerRover.RotationPose) obj;

      boolean result = true;
      result = result && (
          java.lang.Float.floatToIntBits(getXQuat())
          == java.lang.Float.floatToIntBits(
              other.getXQuat()));
      result = result && (
          java.lang.Float.floatToIntBits(getYQuat())
          == java.lang.Float.floatToIntBits(
              other.getYQuat()));
      result = result && (
          java.lang.Float.floatToIntBits(getZQuat())
          == java.lang.Float.floatToIntBits(
              other.getZQuat()));
      result = result && (
          java.lang.Float.floatToIntBits(getWQuat())
          == java.lang.Float.floatToIntBits(
              other.getWQuat()));
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + X_QUAT_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getXQuat());
      hash = (37 * hash) + Y_QUAT_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getYQuat());
      hash = (37 * hash) + Z_QUAT_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getZQuat());
      hash = (37 * hash) + W_QUAT_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getWQuat());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static moonranger_rover.MoonrangerRover.RotationPose parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static moonranger_rover.MoonrangerRover.RotationPose parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static moonranger_rover.MoonrangerRover.RotationPose parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static moonranger_rover.MoonrangerRover.RotationPose parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static moonranger_rover.MoonrangerRover.RotationPose parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static moonranger_rover.MoonrangerRover.RotationPose parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static moonranger_rover.MoonrangerRover.RotationPose parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static moonranger_rover.MoonrangerRover.RotationPose parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static moonranger_rover.MoonrangerRover.RotationPose parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static moonranger_rover.MoonrangerRover.RotationPose parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static moonranger_rover.MoonrangerRover.RotationPose parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static moonranger_rover.MoonrangerRover.RotationPose parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(moonranger_rover.MoonrangerRover.RotationPose prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code moonranger_rover.RotationPose}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:moonranger_rover.RotationPose)
        moonranger_rover.MoonrangerRover.RotationPoseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return moonranger_rover.MoonrangerRover.internal_static_moonranger_rover_RotationPose_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return moonranger_rover.MoonrangerRover.internal_static_moonranger_rover_RotationPose_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                moonranger_rover.MoonrangerRover.RotationPose.class, moonranger_rover.MoonrangerRover.RotationPose.Builder.class);
      }

      // Construct using moonranger_rover.MoonrangerRover.RotationPose.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        xQuat_ = 0F;

        yQuat_ = 0F;

        zQuat_ = 0F;

        wQuat_ = 0F;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return moonranger_rover.MoonrangerRover.internal_static_moonranger_rover_RotationPose_descriptor;
      }

      @java.lang.Override
      public moonranger_rover.MoonrangerRover.RotationPose getDefaultInstanceForType() {
        return moonranger_rover.MoonrangerRover.RotationPose.getDefaultInstance();
      }

      @java.lang.Override
      public moonranger_rover.MoonrangerRover.RotationPose build() {
        moonranger_rover.MoonrangerRover.RotationPose result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public moonranger_rover.MoonrangerRover.RotationPose buildPartial() {
        moonranger_rover.MoonrangerRover.RotationPose result = new moonranger_rover.MoonrangerRover.RotationPose(this);
        result.xQuat_ = xQuat_;
        result.yQuat_ = yQuat_;
        result.zQuat_ = zQuat_;
        result.wQuat_ = wQuat_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof moonranger_rover.MoonrangerRover.RotationPose) {
          return mergeFrom((moonranger_rover.MoonrangerRover.RotationPose)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(moonranger_rover.MoonrangerRover.RotationPose other) {
        if (other == moonranger_rover.MoonrangerRover.RotationPose.getDefaultInstance()) return this;
        if (other.getXQuat() != 0F) {
          setXQuat(other.getXQuat());
        }
        if (other.getYQuat() != 0F) {
          setYQuat(other.getYQuat());
        }
        if (other.getZQuat() != 0F) {
          setZQuat(other.getZQuat());
        }
        if (other.getWQuat() != 0F) {
          setWQuat(other.getWQuat());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        moonranger_rover.MoonrangerRover.RotationPose parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (moonranger_rover.MoonrangerRover.RotationPose) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private float xQuat_ ;
      /**
       * <code>float x_quat = 1;</code>
       */
      public float getXQuat() {
        return xQuat_;
      }
      /**
       * <code>float x_quat = 1;</code>
       */
      public Builder setXQuat(float value) {
        
        xQuat_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float x_quat = 1;</code>
       */
      public Builder clearXQuat() {
        
        xQuat_ = 0F;
        onChanged();
        return this;
      }

      private float yQuat_ ;
      /**
       * <code>float y_quat = 2;</code>
       */
      public float getYQuat() {
        return yQuat_;
      }
      /**
       * <code>float y_quat = 2;</code>
       */
      public Builder setYQuat(float value) {
        
        yQuat_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float y_quat = 2;</code>
       */
      public Builder clearYQuat() {
        
        yQuat_ = 0F;
        onChanged();
        return this;
      }

      private float zQuat_ ;
      /**
       * <code>float z_quat = 3;</code>
       */
      public float getZQuat() {
        return zQuat_;
      }
      /**
       * <code>float z_quat = 3;</code>
       */
      public Builder setZQuat(float value) {
        
        zQuat_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float z_quat = 3;</code>
       */
      public Builder clearZQuat() {
        
        zQuat_ = 0F;
        onChanged();
        return this;
      }

      private float wQuat_ ;
      /**
       * <code>float w_quat = 4;</code>
       */
      public float getWQuat() {
        return wQuat_;
      }
      /**
       * <code>float w_quat = 4;</code>
       */
      public Builder setWQuat(float value) {
        
        wQuat_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float w_quat = 4;</code>
       */
      public Builder clearWQuat() {
        
        wQuat_ = 0F;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:moonranger_rover.RotationPose)
    }

    // @@protoc_insertion_point(class_scope:moonranger_rover.RotationPose)
    private static final moonranger_rover.MoonrangerRover.RotationPose DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new moonranger_rover.MoonrangerRover.RotationPose();
    }

    public static moonranger_rover.MoonrangerRover.RotationPose getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RotationPose>
        PARSER = new com.google.protobuf.AbstractParser<RotationPose>() {
      @java.lang.Override
      public RotationPose parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RotationPose(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RotationPose> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RotationPose> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public moonranger_rover.MoonrangerRover.RotationPose getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PoseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:moonranger_rover.Pose)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>uint64 timestamp_ns = 1;</code>
     */
    long getTimestampNs();

    /**
     * <code>.moonranger_rover.TranslationPose translation = 2;</code>
     */
    boolean hasTranslation();
    /**
     * <code>.moonranger_rover.TranslationPose translation = 2;</code>
     */
    moonranger_rover.MoonrangerRover.TranslationPose getTranslation();
    /**
     * <code>.moonranger_rover.TranslationPose translation = 2;</code>
     */
    moonranger_rover.MoonrangerRover.TranslationPoseOrBuilder getTranslationOrBuilder();

    /**
     * <code>float x_quat = 5;</code>
     */
    float getXQuat();
  }
  /**
   * Protobuf type {@code moonranger_rover.Pose}
   */
  public  static final class Pose extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:moonranger_rover.Pose)
      PoseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Pose.newBuilder() to construct.
    private Pose(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Pose() {
      timestampNs_ = 0L;
      xQuat_ = 0F;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Pose(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              timestampNs_ = input.readUInt64();
              break;
            }
            case 18: {
              moonranger_rover.MoonrangerRover.TranslationPose.Builder subBuilder = null;
              if (translation_ != null) {
                subBuilder = translation_.toBuilder();
              }
              translation_ = input.readMessage(moonranger_rover.MoonrangerRover.TranslationPose.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(translation_);
                translation_ = subBuilder.buildPartial();
              }

              break;
            }
            case 45: {

              xQuat_ = input.readFloat();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return moonranger_rover.MoonrangerRover.internal_static_moonranger_rover_Pose_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return moonranger_rover.MoonrangerRover.internal_static_moonranger_rover_Pose_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              moonranger_rover.MoonrangerRover.Pose.class, moonranger_rover.MoonrangerRover.Pose.Builder.class);
    }

    public static final int TIMESTAMP_NS_FIELD_NUMBER = 1;
    private long timestampNs_;
    /**
     * <code>uint64 timestamp_ns = 1;</code>
     */
    public long getTimestampNs() {
      return timestampNs_;
    }

    public static final int TRANSLATION_FIELD_NUMBER = 2;
    private moonranger_rover.MoonrangerRover.TranslationPose translation_;
    /**
     * <code>.moonranger_rover.TranslationPose translation = 2;</code>
     */
    public boolean hasTranslation() {
      return translation_ != null;
    }
    /**
     * <code>.moonranger_rover.TranslationPose translation = 2;</code>
     */
    public moonranger_rover.MoonrangerRover.TranslationPose getTranslation() {
      return translation_ == null ? moonranger_rover.MoonrangerRover.TranslationPose.getDefaultInstance() : translation_;
    }
    /**
     * <code>.moonranger_rover.TranslationPose translation = 2;</code>
     */
    public moonranger_rover.MoonrangerRover.TranslationPoseOrBuilder getTranslationOrBuilder() {
      return getTranslation();
    }

    public static final int X_QUAT_FIELD_NUMBER = 5;
    private float xQuat_;
    /**
     * <code>float x_quat = 5;</code>
     */
    public float getXQuat() {
      return xQuat_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (timestampNs_ != 0L) {
        output.writeUInt64(1, timestampNs_);
      }
      if (translation_ != null) {
        output.writeMessage(2, getTranslation());
      }
      if (xQuat_ != 0F) {
        output.writeFloat(5, xQuat_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (timestampNs_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, timestampNs_);
      }
      if (translation_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getTranslation());
      }
      if (xQuat_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(5, xQuat_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof moonranger_rover.MoonrangerRover.Pose)) {
        return super.equals(obj);
      }
      moonranger_rover.MoonrangerRover.Pose other = (moonranger_rover.MoonrangerRover.Pose) obj;

      boolean result = true;
      result = result && (getTimestampNs()
          == other.getTimestampNs());
      result = result && (hasTranslation() == other.hasTranslation());
      if (hasTranslation()) {
        result = result && getTranslation()
            .equals(other.getTranslation());
      }
      result = result && (
          java.lang.Float.floatToIntBits(getXQuat())
          == java.lang.Float.floatToIntBits(
              other.getXQuat()));
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TIMESTAMP_NS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTimestampNs());
      if (hasTranslation()) {
        hash = (37 * hash) + TRANSLATION_FIELD_NUMBER;
        hash = (53 * hash) + getTranslation().hashCode();
      }
      hash = (37 * hash) + X_QUAT_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getXQuat());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static moonranger_rover.MoonrangerRover.Pose parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static moonranger_rover.MoonrangerRover.Pose parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static moonranger_rover.MoonrangerRover.Pose parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static moonranger_rover.MoonrangerRover.Pose parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static moonranger_rover.MoonrangerRover.Pose parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static moonranger_rover.MoonrangerRover.Pose parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static moonranger_rover.MoonrangerRover.Pose parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static moonranger_rover.MoonrangerRover.Pose parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static moonranger_rover.MoonrangerRover.Pose parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static moonranger_rover.MoonrangerRover.Pose parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static moonranger_rover.MoonrangerRover.Pose parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static moonranger_rover.MoonrangerRover.Pose parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(moonranger_rover.MoonrangerRover.Pose prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code moonranger_rover.Pose}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:moonranger_rover.Pose)
        moonranger_rover.MoonrangerRover.PoseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return moonranger_rover.MoonrangerRover.internal_static_moonranger_rover_Pose_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return moonranger_rover.MoonrangerRover.internal_static_moonranger_rover_Pose_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                moonranger_rover.MoonrangerRover.Pose.class, moonranger_rover.MoonrangerRover.Pose.Builder.class);
      }

      // Construct using moonranger_rover.MoonrangerRover.Pose.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        timestampNs_ = 0L;

        if (translationBuilder_ == null) {
          translation_ = null;
        } else {
          translation_ = null;
          translationBuilder_ = null;
        }
        xQuat_ = 0F;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return moonranger_rover.MoonrangerRover.internal_static_moonranger_rover_Pose_descriptor;
      }

      @java.lang.Override
      public moonranger_rover.MoonrangerRover.Pose getDefaultInstanceForType() {
        return moonranger_rover.MoonrangerRover.Pose.getDefaultInstance();
      }

      @java.lang.Override
      public moonranger_rover.MoonrangerRover.Pose build() {
        moonranger_rover.MoonrangerRover.Pose result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public moonranger_rover.MoonrangerRover.Pose buildPartial() {
        moonranger_rover.MoonrangerRover.Pose result = new moonranger_rover.MoonrangerRover.Pose(this);
        result.timestampNs_ = timestampNs_;
        if (translationBuilder_ == null) {
          result.translation_ = translation_;
        } else {
          result.translation_ = translationBuilder_.build();
        }
        result.xQuat_ = xQuat_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof moonranger_rover.MoonrangerRover.Pose) {
          return mergeFrom((moonranger_rover.MoonrangerRover.Pose)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(moonranger_rover.MoonrangerRover.Pose other) {
        if (other == moonranger_rover.MoonrangerRover.Pose.getDefaultInstance()) return this;
        if (other.getTimestampNs() != 0L) {
          setTimestampNs(other.getTimestampNs());
        }
        if (other.hasTranslation()) {
          mergeTranslation(other.getTranslation());
        }
        if (other.getXQuat() != 0F) {
          setXQuat(other.getXQuat());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        moonranger_rover.MoonrangerRover.Pose parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (moonranger_rover.MoonrangerRover.Pose) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long timestampNs_ ;
      /**
       * <code>uint64 timestamp_ns = 1;</code>
       */
      public long getTimestampNs() {
        return timestampNs_;
      }
      /**
       * <code>uint64 timestamp_ns = 1;</code>
       */
      public Builder setTimestampNs(long value) {
        
        timestampNs_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 timestamp_ns = 1;</code>
       */
      public Builder clearTimestampNs() {
        
        timestampNs_ = 0L;
        onChanged();
        return this;
      }

      private moonranger_rover.MoonrangerRover.TranslationPose translation_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          moonranger_rover.MoonrangerRover.TranslationPose, moonranger_rover.MoonrangerRover.TranslationPose.Builder, moonranger_rover.MoonrangerRover.TranslationPoseOrBuilder> translationBuilder_;
      /**
       * <code>.moonranger_rover.TranslationPose translation = 2;</code>
       */
      public boolean hasTranslation() {
        return translationBuilder_ != null || translation_ != null;
      }
      /**
       * <code>.moonranger_rover.TranslationPose translation = 2;</code>
       */
      public moonranger_rover.MoonrangerRover.TranslationPose getTranslation() {
        if (translationBuilder_ == null) {
          return translation_ == null ? moonranger_rover.MoonrangerRover.TranslationPose.getDefaultInstance() : translation_;
        } else {
          return translationBuilder_.getMessage();
        }
      }
      /**
       * <code>.moonranger_rover.TranslationPose translation = 2;</code>
       */
      public Builder setTranslation(moonranger_rover.MoonrangerRover.TranslationPose value) {
        if (translationBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          translation_ = value;
          onChanged();
        } else {
          translationBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.moonranger_rover.TranslationPose translation = 2;</code>
       */
      public Builder setTranslation(
          moonranger_rover.MoonrangerRover.TranslationPose.Builder builderForValue) {
        if (translationBuilder_ == null) {
          translation_ = builderForValue.build();
          onChanged();
        } else {
          translationBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.moonranger_rover.TranslationPose translation = 2;</code>
       */
      public Builder mergeTranslation(moonranger_rover.MoonrangerRover.TranslationPose value) {
        if (translationBuilder_ == null) {
          if (translation_ != null) {
            translation_ =
              moonranger_rover.MoonrangerRover.TranslationPose.newBuilder(translation_).mergeFrom(value).buildPartial();
          } else {
            translation_ = value;
          }
          onChanged();
        } else {
          translationBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.moonranger_rover.TranslationPose translation = 2;</code>
       */
      public Builder clearTranslation() {
        if (translationBuilder_ == null) {
          translation_ = null;
          onChanged();
        } else {
          translation_ = null;
          translationBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.moonranger_rover.TranslationPose translation = 2;</code>
       */
      public moonranger_rover.MoonrangerRover.TranslationPose.Builder getTranslationBuilder() {
        
        onChanged();
        return getTranslationFieldBuilder().getBuilder();
      }
      /**
       * <code>.moonranger_rover.TranslationPose translation = 2;</code>
       */
      public moonranger_rover.MoonrangerRover.TranslationPoseOrBuilder getTranslationOrBuilder() {
        if (translationBuilder_ != null) {
          return translationBuilder_.getMessageOrBuilder();
        } else {
          return translation_ == null ?
              moonranger_rover.MoonrangerRover.TranslationPose.getDefaultInstance() : translation_;
        }
      }
      /**
       * <code>.moonranger_rover.TranslationPose translation = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          moonranger_rover.MoonrangerRover.TranslationPose, moonranger_rover.MoonrangerRover.TranslationPose.Builder, moonranger_rover.MoonrangerRover.TranslationPoseOrBuilder> 
          getTranslationFieldBuilder() {
        if (translationBuilder_ == null) {
          translationBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              moonranger_rover.MoonrangerRover.TranslationPose, moonranger_rover.MoonrangerRover.TranslationPose.Builder, moonranger_rover.MoonrangerRover.TranslationPoseOrBuilder>(
                  getTranslation(),
                  getParentForChildren(),
                  isClean());
          translation_ = null;
        }
        return translationBuilder_;
      }

      private float xQuat_ ;
      /**
       * <code>float x_quat = 5;</code>
       */
      public float getXQuat() {
        return xQuat_;
      }
      /**
       * <code>float x_quat = 5;</code>
       */
      public Builder setXQuat(float value) {
        
        xQuat_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float x_quat = 5;</code>
       */
      public Builder clearXQuat() {
        
        xQuat_ = 0F;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:moonranger_rover.Pose)
    }

    // @@protoc_insertion_point(class_scope:moonranger_rover.Pose)
    private static final moonranger_rover.MoonrangerRover.Pose DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new moonranger_rover.MoonrangerRover.Pose();
    }

    public static moonranger_rover.MoonrangerRover.Pose getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Pose>
        PARSER = new com.google.protobuf.AbstractParser<Pose>() {
      @java.lang.Override
      public Pose parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Pose(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Pose> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Pose> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public moonranger_rover.MoonrangerRover.Pose getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_moonranger_rover_Goal_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_moonranger_rover_Goal_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_moonranger_rover_TranslationPose_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_moonranger_rover_TranslationPose_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_moonranger_rover_RotationPose_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_moonranger_rover_RotationPose_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_moonranger_rover_Pose_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_moonranger_rover_Pose_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026moonranger_rover.proto\022\020moonranger_rov" +
      "er\"q\n\004Goal\022\026\n\016x_coordinate_m\030\001 \001(\002\022\026\n\016y_" +
      "coordinate_m\030\002 \001(\002\022\017\n\007x_rad_m\030\003 \001(\002\022\017\n\007y" +
      "_rad_m\030\004 \001(\002\022\027\n\017orientation_rad\030\005 \001(\002\"8\n" +
      "\017TranslationPose\022\013\n\003x_m\030\001 \001(\002\022\013\n\003y_m\030\002 \001" +
      "(\002\022\013\n\003z_m\030\003 \001(\002\"N\n\014RotationPose\022\016\n\006x_qua" +
      "t\030\001 \001(\002\022\016\n\006y_quat\030\002 \001(\002\022\016\n\006z_quat\030\003 \001(\002\022" +
      "\016\n\006w_quat\030\004 \001(\002\"d\n\004Pose\022\024\n\014timestamp_ns\030" +
      "\001 \001(\004\0226\n\013translation\030\002 \001(\0132!.moonranger_" +
      "rover.TranslationPose\022\016\n\006x_quat\030\005 \001(\002b\006p" +
      "roto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_moonranger_rover_Goal_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_moonranger_rover_Goal_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_moonranger_rover_Goal_descriptor,
        new java.lang.String[] { "XCoordinateM", "YCoordinateM", "XRadM", "YRadM", "OrientationRad", });
    internal_static_moonranger_rover_TranslationPose_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_moonranger_rover_TranslationPose_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_moonranger_rover_TranslationPose_descriptor,
        new java.lang.String[] { "XM", "YM", "ZM", });
    internal_static_moonranger_rover_RotationPose_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_moonranger_rover_RotationPose_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_moonranger_rover_RotationPose_descriptor,
        new java.lang.String[] { "XQuat", "YQuat", "ZQuat", "WQuat", });
    internal_static_moonranger_rover_Pose_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_moonranger_rover_Pose_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_moonranger_rover_Pose_descriptor,
        new java.lang.String[] { "TimestampNs", "Translation", "XQuat", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
