/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.6-dev */

#ifndef PB_MOONRANGER_ROVER_MOONRANGER_ROVER_PB_H_INCLUDED
#define PB_MOONRANGER_ROVER_MOONRANGER_ROVER_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _moonranger_rover_Goal { 
    float x_coordinate_m; 
    float y_coordinate_m; 
    float x_rad_m; 
    float y_rad_m; 
    float orientation_rad; 
} moonranger_rover_Goal;

typedef struct _moonranger_rover_RotationPose { 
    float x_quat; 
    float y_quat; 
    float z_quat; 
    float w_quat; 
} moonranger_rover_RotationPose;

typedef struct _moonranger_rover_TranslationPose { 
    float x_m; 
    float y_m; 
    float z_m; 
} moonranger_rover_TranslationPose;

typedef struct _moonranger_rover_Pose { 
    uint64_t timestamp_ns; 
    bool has_translation;
    moonranger_rover_TranslationPose translation; 
    float x_quat; 
} moonranger_rover_Pose;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define moonranger_rover_Goal_init_default       {0, 0, 0, 0, 0}
#define moonranger_rover_TranslationPose_init_default {0, 0, 0}
#define moonranger_rover_RotationPose_init_default {0, 0, 0, 0}
#define moonranger_rover_Pose_init_default       {0, false, moonranger_rover_TranslationPose_init_default, 0}
#define moonranger_rover_Goal_init_zero          {0, 0, 0, 0, 0}
#define moonranger_rover_TranslationPose_init_zero {0, 0, 0}
#define moonranger_rover_RotationPose_init_zero  {0, 0, 0, 0}
#define moonranger_rover_Pose_init_zero          {0, false, moonranger_rover_TranslationPose_init_zero, 0}

/* Field tags (for use in manual encoding/decoding) */
#define moonranger_rover_Goal_x_coordinate_m_tag 1
#define moonranger_rover_Goal_y_coordinate_m_tag 2
#define moonranger_rover_Goal_x_rad_m_tag        3
#define moonranger_rover_Goal_y_rad_m_tag        4
#define moonranger_rover_Goal_orientation_rad_tag 5
#define moonranger_rover_RotationPose_x_quat_tag 1
#define moonranger_rover_RotationPose_y_quat_tag 2
#define moonranger_rover_RotationPose_z_quat_tag 3
#define moonranger_rover_RotationPose_w_quat_tag 4
#define moonranger_rover_TranslationPose_x_m_tag 1
#define moonranger_rover_TranslationPose_y_m_tag 2
#define moonranger_rover_TranslationPose_z_m_tag 3
#define moonranger_rover_Pose_timestamp_ns_tag   1
#define moonranger_rover_Pose_translation_tag    2
#define moonranger_rover_Pose_x_quat_tag         5

/* Struct field encoding specification for nanopb */
#define moonranger_rover_Goal_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    x_coordinate_m,    1) \
X(a, STATIC,   SINGULAR, FLOAT,    y_coordinate_m,    2) \
X(a, STATIC,   SINGULAR, FLOAT,    x_rad_m,           3) \
X(a, STATIC,   SINGULAR, FLOAT,    y_rad_m,           4) \
X(a, STATIC,   SINGULAR, FLOAT,    orientation_rad,   5)
#define moonranger_rover_Goal_CALLBACK NULL
#define moonranger_rover_Goal_DEFAULT NULL

#define moonranger_rover_TranslationPose_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    x_m,               1) \
X(a, STATIC,   SINGULAR, FLOAT,    y_m,               2) \
X(a, STATIC,   SINGULAR, FLOAT,    z_m,               3)
#define moonranger_rover_TranslationPose_CALLBACK NULL
#define moonranger_rover_TranslationPose_DEFAULT NULL

#define moonranger_rover_RotationPose_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    x_quat,            1) \
X(a, STATIC,   SINGULAR, FLOAT,    y_quat,            2) \
X(a, STATIC,   SINGULAR, FLOAT,    z_quat,            3) \
X(a, STATIC,   SINGULAR, FLOAT,    w_quat,            4)
#define moonranger_rover_RotationPose_CALLBACK NULL
#define moonranger_rover_RotationPose_DEFAULT NULL

#define moonranger_rover_Pose_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   timestamp_ns,      1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  translation,       2) \
X(a, STATIC,   SINGULAR, FLOAT,    x_quat,            5)
#define moonranger_rover_Pose_CALLBACK NULL
#define moonranger_rover_Pose_DEFAULT NULL
#define moonranger_rover_Pose_translation_MSGTYPE moonranger_rover_TranslationPose

extern const pb_msgdesc_t moonranger_rover_Goal_msg;
extern const pb_msgdesc_t moonranger_rover_TranslationPose_msg;
extern const pb_msgdesc_t moonranger_rover_RotationPose_msg;
extern const pb_msgdesc_t moonranger_rover_Pose_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define moonranger_rover_Goal_fields &moonranger_rover_Goal_msg
#define moonranger_rover_TranslationPose_fields &moonranger_rover_TranslationPose_msg
#define moonranger_rover_RotationPose_fields &moonranger_rover_RotationPose_msg
#define moonranger_rover_Pose_fields &moonranger_rover_Pose_msg

/* Maximum encoded size of messages (where known) */
#define moonranger_rover_Goal_size               25
#define moonranger_rover_Pose_size               33
#define moonranger_rover_RotationPose_size       20
#define moonranger_rover_TranslationPose_size    15

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
