/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.6-dev */

#include "moonranger_rover.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(moonranger_rover_Goal, moonranger_rover_Goal, AUTO)


PB_BIND(moonranger_rover_TranslationPose, moonranger_rover_TranslationPose, AUTO)


PB_BIND(moonranger_rover_RotationPose, moonranger_rover_RotationPose, AUTO)


PB_BIND(moonranger_rover_Pose, moonranger_rover_Pose, AUTO)



