# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: moonranger_rover.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='moonranger_rover.proto',
  package='moonranger_rover',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x16moonranger_rover.proto\x12\x10moonranger_rover\"q\n\x04Goal\x12\x16\n\x0ex_coordinate_m\x18\x01 \x01(\x02\x12\x16\n\x0ey_coordinate_m\x18\x02 \x01(\x02\x12\x0f\n\x07x_rad_m\x18\x03 \x01(\x02\x12\x0f\n\x07y_rad_m\x18\x04 \x01(\x02\x12\x17\n\x0forientation_rad\x18\x05 \x01(\x02\"8\n\x0fTranslationPose\x12\x0b\n\x03x_m\x18\x01 \x01(\x02\x12\x0b\n\x03y_m\x18\x02 \x01(\x02\x12\x0b\n\x03z_m\x18\x03 \x01(\x02\"N\n\x0cRotationPose\x12\x0e\n\x06x_quat\x18\x01 \x01(\x02\x12\x0e\n\x06y_quat\x18\x02 \x01(\x02\x12\x0e\n\x06z_quat\x18\x03 \x01(\x02\x12\x0e\n\x06w_quat\x18\x04 \x01(\x02\"d\n\x04Pose\x12\x14\n\x0ctimestamp_ns\x18\x01 \x01(\x04\x12\x36\n\x0btranslation\x18\x02 \x01(\x0b\x32!.moonranger_rover.TranslationPose\x12\x0e\n\x06x_quat\x18\x05 \x01(\x02\x62\x06proto3')
)




_GOAL = _descriptor.Descriptor(
  name='Goal',
  full_name='moonranger_rover.Goal',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x_coordinate_m', full_name='moonranger_rover.Goal.x_coordinate_m', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y_coordinate_m', full_name='moonranger_rover.Goal.y_coordinate_m', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='x_rad_m', full_name='moonranger_rover.Goal.x_rad_m', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y_rad_m', full_name='moonranger_rover.Goal.y_rad_m', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='orientation_rad', full_name='moonranger_rover.Goal.orientation_rad', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=44,
  serialized_end=157,
)


_TRANSLATIONPOSE = _descriptor.Descriptor(
  name='TranslationPose',
  full_name='moonranger_rover.TranslationPose',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x_m', full_name='moonranger_rover.TranslationPose.x_m', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y_m', full_name='moonranger_rover.TranslationPose.y_m', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='z_m', full_name='moonranger_rover.TranslationPose.z_m', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=159,
  serialized_end=215,
)


_ROTATIONPOSE = _descriptor.Descriptor(
  name='RotationPose',
  full_name='moonranger_rover.RotationPose',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x_quat', full_name='moonranger_rover.RotationPose.x_quat', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y_quat', full_name='moonranger_rover.RotationPose.y_quat', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='z_quat', full_name='moonranger_rover.RotationPose.z_quat', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='w_quat', full_name='moonranger_rover.RotationPose.w_quat', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=217,
  serialized_end=295,
)


_POSE = _descriptor.Descriptor(
  name='Pose',
  full_name='moonranger_rover.Pose',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp_ns', full_name='moonranger_rover.Pose.timestamp_ns', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='translation', full_name='moonranger_rover.Pose.translation', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='x_quat', full_name='moonranger_rover.Pose.x_quat', index=2,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=297,
  serialized_end=397,
)

_POSE.fields_by_name['translation'].message_type = _TRANSLATIONPOSE
DESCRIPTOR.message_types_by_name['Goal'] = _GOAL
DESCRIPTOR.message_types_by_name['TranslationPose'] = _TRANSLATIONPOSE
DESCRIPTOR.message_types_by_name['RotationPose'] = _ROTATIONPOSE
DESCRIPTOR.message_types_by_name['Pose'] = _POSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Goal = _reflection.GeneratedProtocolMessageType('Goal', (_message.Message,), dict(
  DESCRIPTOR = _GOAL,
  __module__ = 'moonranger_rover_pb2'
  # @@protoc_insertion_point(class_scope:moonranger_rover.Goal)
  ))
_sym_db.RegisterMessage(Goal)

TranslationPose = _reflection.GeneratedProtocolMessageType('TranslationPose', (_message.Message,), dict(
  DESCRIPTOR = _TRANSLATIONPOSE,
  __module__ = 'moonranger_rover_pb2'
  # @@protoc_insertion_point(class_scope:moonranger_rover.TranslationPose)
  ))
_sym_db.RegisterMessage(TranslationPose)

RotationPose = _reflection.GeneratedProtocolMessageType('RotationPose', (_message.Message,), dict(
  DESCRIPTOR = _ROTATIONPOSE,
  __module__ = 'moonranger_rover_pb2'
  # @@protoc_insertion_point(class_scope:moonranger_rover.RotationPose)
  ))
_sym_db.RegisterMessage(RotationPose)

Pose = _reflection.GeneratedProtocolMessageType('Pose', (_message.Message,), dict(
  DESCRIPTOR = _POSE,
  __module__ = 'moonranger_rover_pb2'
  # @@protoc_insertion_point(class_scope:moonranger_rover.Pose)
  ))
_sym_db.RegisterMessage(Pose)


# @@protoc_insertion_point(module_scope)
